// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/server_handlers/handlers.go

// Package mock_serverhandlers is a generated GoMock package.
package mock_serverhandlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/maliven1/metrics/internal/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddStructMetric mocks base method.
func (m *MockService) AddStructMetric(metric models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStructMetric", metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStructMetric indicates an expected call of AddStructMetric.
func (mr *MockServiceMockRecorder) AddStructMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStructMetric", reflect.TypeOf((*MockService)(nil).AddStructMetric), metric)
}

// CheckAddPath mocks base method.
func (m *MockService) CheckAddPath(pathSplit []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAddPath", pathSplit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAddPath indicates an expected call of CheckAddPath.
func (mr *MockServiceMockRecorder) CheckAddPath(pathSplit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAddPath", reflect.TypeOf((*MockService)(nil).CheckAddPath), pathSplit)
}

// GetAllMetrics mocks base method.
func (m *MockService) GetAllMetrics() (map[string]int64, map[string]float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMetrics")
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(map[string]float64)
	return ret0, ret1
}

// GetAllMetrics indicates an expected call of GetAllMetrics.
func (mr *MockServiceMockRecorder) GetAllMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMetrics", reflect.TypeOf((*MockService)(nil).GetAllMetrics))
}

// GetMetric mocks base method.
func (m *MockService) GetMetric(pathSplit []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", pathSplit)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockServiceMockRecorder) GetMetric(pathSplit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockService)(nil).GetMetric), pathSplit)
}

// GetStructMetric mocks base method.
func (m *MockService) GetStructMetric(metric models.Metrics) (models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructMetric", metric)
	ret0, _ := ret[0].(models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructMetric indicates an expected call of GetStructMetric.
func (mr *MockServiceMockRecorder) GetStructMetric(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructMetric", reflect.TypeOf((*MockService)(nil).GetStructMetric), metric)
}

// SetMetrics mocks base method.
func (m *MockService) SetMetrics(metrics []models.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetrics", metrics)
}

// SetMetrics indicates an expected call of SetMetrics.
func (mr *MockServiceMockRecorder) SetMetrics(metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetrics", reflect.TypeOf((*MockService)(nil).SetMetrics), metrics)
}

// MockPostgreService is a mock of PostgreService interface.
type MockPostgreService struct {
	ctrl     *gomock.Controller
	recorder *MockPostgreServiceMockRecorder
}

// MockPostgreServiceMockRecorder is the mock recorder for MockPostgreService.
type MockPostgreServiceMockRecorder struct {
	mock *MockPostgreService
}

// NewMockPostgreService creates a new mock instance.
func NewMockPostgreService(ctrl *gomock.Controller) *MockPostgreService {
	mock := &MockPostgreService{ctrl: ctrl}
	mock.recorder = &MockPostgreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgreService) EXPECT() *MockPostgreServiceMockRecorder {
	return m.recorder
}

// CheckConnection mocks base method.
func (m *MockPostgreService) CheckConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnection indicates an expected call of CheckConnection.
func (mr *MockPostgreServiceMockRecorder) CheckConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnection", reflect.TypeOf((*MockPostgreService)(nil).CheckConnection))
}
