// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemRepo is a mock of MemRepo interface.
type MockMemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMemRepoMockRecorder
}

// MockMemRepoMockRecorder is the mock recorder for MockMemRepo.
type MockMemRepoMockRecorder struct {
	mock *MockMemRepo
}

// NewMockMemRepo creates a new mock instance.
func NewMockMemRepo(ctrl *gomock.Controller) *MockMemRepo {
	mock := &MockMemRepo{ctrl: ctrl}
	mock.recorder = &MockMemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemRepo) EXPECT() *MockMemRepoMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMemRepo) AddCounter(key string, value int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCounter", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMemRepoMockRecorder) AddCounter(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMemRepo)(nil).AddCounter), key, value)
}

// CheckCounter mocks base method.
func (m *MockMemRepo) CheckCounter(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCounter", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckCounter indicates an expected call of CheckCounter.
func (mr *MockMemRepoMockRecorder) CheckCounter(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCounter", reflect.TypeOf((*MockMemRepo)(nil).CheckCounter), key)
}

// CheckItemGauge mocks base method.
func (m *MockMemRepo) CheckItemGauge(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckItemGauge", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckItemGauge indicates an expected call of CheckItemGauge.
func (mr *MockMemRepoMockRecorder) CheckItemGauge(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckItemGauge", reflect.TypeOf((*MockMemRepo)(nil).CheckItemGauge), key)
}

// GetCounter mocks base method.
func (m *MockMemRepo) GetCounter() map[string]int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter")
	ret0, _ := ret[0].(map[string]int64)
	return ret0
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMemRepoMockRecorder) GetCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMemRepo)(nil).GetCounter))
}

// GetGauge mocks base method.
func (m *MockMemRepo) GetGauge() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMemRepoMockRecorder) GetGauge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMemRepo)(nil).GetGauge))
}

// GetItemCounter mocks base method.
func (m *MockMemRepo) GetItemCounter(s string) (string, int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemCounter", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	return ret0, ret1
}

// GetItemCounter indicates an expected call of GetItemCounter.
func (mr *MockMemRepoMockRecorder) GetItemCounter(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemCounter", reflect.TypeOf((*MockMemRepo)(nil).GetItemCounter), s)
}

// GetItemGauge mocks base method.
func (m *MockMemRepo) GetItemGauge(s string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemGauge", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// GetItemGauge indicates an expected call of GetItemGauge.
func (mr *MockMemRepoMockRecorder) GetItemGauge(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemGauge", reflect.TypeOf((*MockMemRepo)(nil).GetItemGauge), s)
}

// SetCounter mocks base method.
func (m *MockMemRepo) SetCounter(key string, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCounter", key, value)
}

// SetCounter indicates an expected call of SetCounter.
func (mr *MockMemRepoMockRecorder) SetCounter(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCounter", reflect.TypeOf((*MockMemRepo)(nil).SetCounter), key, value)
}

// SetGauge mocks base method.
func (m *MockMemRepo) SetGauge(key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGauge", key, value)
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockMemRepoMockRecorder) SetGauge(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockMemRepo)(nil).SetGauge), key, value)
}
