// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemStorage is a mock of MemStorage interface.
type MockMemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMemStorageMockRecorder
	isgomock struct{}
}

// MockMemStorageMockRecorder is the mock recorder for MockMemStorage.
type MockMemStorageMockRecorder struct {
	mock *MockMemStorage
}

// NewMockMemStorage creates a new mock instance.
func NewMockMemStorage(ctrl *gomock.Controller) *MockMemStorage {
	mock := &MockMemStorage{ctrl: ctrl}
	mock.recorder = &MockMemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemStorage) EXPECT() *MockMemStorageMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockMemStorage) AddCounter(key string, value int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCounter", key, value)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockMemStorageMockRecorder) AddCounter(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockMemStorage)(nil).AddCounter), key, value)
}

// CheckCounter mocks base method.
func (m *MockMemStorage) CheckCounter(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCounter", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckCounter indicates an expected call of CheckCounter.
func (mr *MockMemStorageMockRecorder) CheckCounter(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCounter", reflect.TypeOf((*MockMemStorage)(nil).CheckCounter), key)
}

// CheckItemGauge mocks base method.
func (m *MockMemStorage) CheckItemGauge(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckItemGauge", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckItemGauge indicates an expected call of CheckItemGauge.
func (mr *MockMemStorageMockRecorder) CheckItemGauge(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckItemGauge", reflect.TypeOf((*MockMemStorage)(nil).CheckItemGauge), key)
}

// GetCounter mocks base method.
func (m *MockMemStorage) GetCounter() map[string]int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter")
	ret0, _ := ret[0].(map[string]int64)
	return ret0
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMemStorageMockRecorder) GetCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMemStorage)(nil).GetCounter))
}

// GetGauge mocks base method.
func (m *MockMemStorage) GetGauge() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMemStorageMockRecorder) GetGauge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMemStorage)(nil).GetGauge))
}

// GetItemCounter mocks base method.
func (m *MockMemStorage) GetItemCounter(s string) (string, int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemCounter", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	return ret0, ret1
}

// GetItemCounter indicates an expected call of GetItemCounter.
func (mr *MockMemStorageMockRecorder) GetItemCounter(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemCounter", reflect.TypeOf((*MockMemStorage)(nil).GetItemCounter), s)
}

// GetItemGauge mocks base method.
func (m *MockMemStorage) GetItemGauge(s string) (string, float64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemGauge", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(float64)
	return ret0, ret1
}

// GetItemGauge indicates an expected call of GetItemGauge.
func (mr *MockMemStorageMockRecorder) GetItemGauge(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemGauge", reflect.TypeOf((*MockMemStorage)(nil).GetItemGauge), s)
}

// SetCounter mocks base method.
func (m *MockMemStorage) SetCounter(key string, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCounter", key, value)
}

// SetCounter indicates an expected call of SetCounter.
func (mr *MockMemStorageMockRecorder) SetCounter(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCounter", reflect.TypeOf((*MockMemStorage)(nil).SetCounter), key, value)
}

// SetGauge mocks base method.
func (m *MockMemStorage) SetGauge(key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGauge", key, value)
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockMemStorageMockRecorder) SetGauge(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockMemStorage)(nil).SetGauge), key, value)
}
